name: WF_Dependencies

on:
  push:
    branches:
      - main

  workflow_dispatch:
      
permissions:
  id-token: write
  contents: read


jobs:
    build_infra:
        runs-on: ubuntu-latest

        outputs:
            lambda_name: ${{ steps.tf_outputs.outputs.lambda_name }}
            bucket_name: ${{ steps.tf_outputs.outputs.bucket_name }}

        steps:
            - uses: actions/checkout@v7
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-region: us-east-1
                role-to-assume: ${{ secrets.AWS_ROLE }}

            - uses: hashicorp/setup-terraform@v4
              with:
                terraform_version: "1.15.4"

            - name: Terrafrom init
              run: terraform init
              working-directory: infra/environments/dev

            - name: Terrafrom apply
              run: terraform apply -auto-approve -var-file="terraform.tfvars"
              working-directory: infra/environments/dev

            - name: Terraform read outputs
              id: tf_outputs
              run: |
                echo "bucket_name=$(terraform output -raw bucket_name)" >> $GITHUB_OUTPUT
                echo "lambda_name=$(terraform output -raw lambda_name)" >> $GITHUB_OUTPUT
                
              working-directory: infra/environments/dev
              

    deploy_lambda:

        needs: build_infra
        
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - name: Create Lambda package
              run: | 
                mkdir build
                mv lambda_backend.mjs build/lambda_backend.mjs
              working-directory: backend
            

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                aws-region: us-east-1
                role-to-assume: ${{ secrets.AWS_ROLE }}

            - name: Deploy Lambda Function
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                function-name: ${{needs.build_infra.outputs.lambda_name}}
                code-artifacts-dir: backend/build
                handler: lambda_backend.handler
                runtime: nodejs22.x
                # Add any additional inputs this action supports

    deploy_s3:
        needs: build_infra
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v7

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v6.1.0
            with:
              aws-region: us-east-1
              role-to-assume: ${{ secrets.AWS_ROLE }}

          - name: Upload s3
            run: aws s3 sync frontend s3://${{needs.build_infra.outputs.lambda_name}} --exclude "tests/*"

